on: [push]
jobs:
  JmeterDockerRun:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3  # Update to the latest version

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2  # Update to the latest version

      - name: Build and run JMeter Docker container
        run: |
          docker run --rm -v "$(pwd):/tests" justb4/jmeter:5.5 -n -t /tests/tests/your_test.jmx -l /tests/results.jtl
          
      - name: Upload JMeter results
        uses: actions/upload-artifact@v3  # Update to the latest version
        with:
          name: jmeter-results
          path: results.jtl
