on: [push]
jobs:
  JmeterDockerRun:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and run JMeter Docker container
        run: |
          docker run --rm -v "${{ github.workspace }}:/tests" justb4/jmeter:5.5 -n -t /tests/tests/S01_SimpleExample.jmx -l /tests/results.jtl
          
      - name: Upload JMeter results
        uses: actions/upload-artifact@v3
        with:
          name: jmeter-results
          path: results.jtl
