on: [push]

jobs:
  JmeterDockerRun:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Create Docker Network
        run: |
          docker network create jmeter-network

      - name: Start JMeter Slave Nodes
        run: |
          # Start three JMeter slave nodes in detached mode
          docker run -d --name jmeter-slave1 --network jmeter-network justb4/jmeter:5.5 -s
          docker run -d --name jmeter-slave2 --network jmeter-network justb4/jmeter:5.5 -s
          docker run -d --name jmeter-slave3 --network jmeter-network justb4/jmeter:5.5 -s

      - name: Start JMeter Master Node
        run: |
          # Start JMeter master node and connect to the slave nodes
          docker run --rm --name jmeter-master --network jmeter-network -v "${{ github.workspace }}:/tests" justb4/jmeter:5.5 \
            -n -t /tests/tests/S01_SimpleExample.jmx \
            -l /tests/results.jtl \
            -R jmeter-slave1,jmeter-slave2,jmeter-slave3 \
            -e -o /tests/html_report

      - name: Upload JMeter Results
        uses: actions/upload-artifact@v3
        with:
          name: jmeter-results
          path: results.jtl

      - name: Upload JMeter HTML Report
        uses: actions/upload-artifact@v3
        with:
          name: jmeter-html-report
          path: html_report

      - name: Clean up Docker containers
        run: |
          docker stop jmeter-slave1 jmeter-slave2 jmeter-slave3 jmeter-master
          docker rm jmeter-slave1 jmeter-slave2 jmeter-slave3 jmeter-master
          docker network rm jmeter-network
