on: [push]
jobs:
  JmeterDockerRun:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Start JMeter Slave Containers
        run: |
          # Start three JMeter slave containers
          docker run -d --name jmeter-slave1 justb4/jmeter:5.5 \
            -Djava.rmi.server.hostname=jmeter-slave1 \
            -Jserver.port=1099 \
            -Jclient.rmi.localport=40000 \
            -Djava.rmi.server.useLocalHostname=false \
            -Djava.rmi.server.ssl=false
          
          docker run -d --name jmeter-slave2 justb4/jmeter:5.5 \
            -Djava.rmi.server.hostname=jmeter-slave2 \
            -Jserver.port=1099 \
            -Jclient.rmi.localport=40001 \
            -Djava.rmi.server.useLocalHostname=false \
            -Djava.rmi.server.ssl=false
          
          docker run -d --name jmeter-slave3 justb4/jmeter:5.5 \
            -Djava.rmi.server.hostname=jmeter-slave3 \
            -Jserver.port=1099 \
            -Jclient.rmi.localport=40002 \
            -Djava.rmi.server.useLocalHostname=false \
            -Djava.rmi.server.ssl=false

      - name: Wait for Slaves to Start
        run: |
          # Wait for a few seconds to ensure the slave containers are fully up
          sleep 10

      - name: Build and run JMeter Master Container
        run: |
          # Run the JMeter master to execute the test using the container names
          docker run --rm -v "${{ github.workspace }}:/tests" justb4/jmeter:5.5 \
            -n -t /tests/tests/S01_SimpleExample.jmx -l /tests/results.jtl \
            -R jmeter-slave1,jmeter-slave2,jmeter-slave3

      - name: Upload JMeter Results
        uses: actions/upload-artifact@v3
        with:
          name: jmeter-results
          path: results.jtl
