on: [push]

jobs:
  JmeterDockerRun:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Create Docker Network
        run: |
          docker network create jmeter-network

      - name: Generate rmi_keystore.jks
        run: |
          keytool -genkeypair -alias jmeter -keyalg RSA -keystore rmi_keystore.jks -keysize 2048 -dname "CN=localhost, OU=MyOrganization, O=MyCompany, L=City, S=State, C=Country" -storepass password -keypass password -noprompt

      - name: Verify Keystore Format
        run: |
          keytool -list -v -keystore rmi_keystore.jks -storepass password

      - name: Start JMeter Slave Nodes
        run: |
          for i in {1..3}; do
            docker run -d --name jmeter-slave$i --network jmeter-network -v "${{ github.workspace }}/rmi_keystore.jks:/bin/rmi_keystore.jks" justb4/jmeter:5.5 -s -Jserver.rmi.ssl.keystore.file=/bin/rmi_keystore.jks -Jserver.rmi.ssl.keystore.pass=password
          done

      - name: Start JMeter Master Node
        run: |
          docker run --rm --name jmeter-master --network jmeter-network -v "${{ github.workspace }}:/tests" -v "${{ github.workspace }}/rmi_keystore.jks:/bin/rmi_keystore.jks" justb4/jmeter:5.5 \
            -n -t /tests/tests/S01_SimpleExample.jmx \
            -l /tests/results.jtl \
            -R jmeter-slave1,jmeter-slave2,jmeter-slave3 \
            -e -o /tests/html_report \
            -Jserver.rmi.ssl.keystore.file=/bin/rmi_keystore.jks \
            -Jserver.rmi.ssl.keystore.pass=password

      - name: Upload JMeter Results
        uses: actions/upload-artifact@v3
        with:
          name: jmeter-results
          path: results.jtl

      - name: Upload JMeter HTML Report
        uses: actions/upload-artifact@v3
        with:
          name: jmeter-html-report
          path: html_report

      - name: Clean up Docker containers
        run: |
          docker stop jmeter-slave1 jmeter-slave2 jmeter-slave3 jmeter-master
          docker rm jmeter-slave1 jmeter-slave2 jmeter-slave3 jmeter-master
          docker network rm jmeter-network
